# Generated by Django 6.0.5 on 2026-06-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='created_at',
        ),
        migrations.AddField(
            model_name='venue',
            name='bride_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='groom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
