# Generated by Django 6.0.5 on 2026-06-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_venue_created_at_venue_bride_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], default='Available', max_length=20),
        ),
    ]
