# Generated by Django 6.0.5 on 2026-06-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_venue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('add_users', models.BooleanField(default=False)),
                ('edit_users', models.BooleanField(default=False)),
                ('delete_users', models.BooleanField(default=False)),
                ('manage_bookings', models.BooleanField(default=False)),
                ('manage_venues', models.BooleanField(default=False)),
            ],
        ),
    ]
