# Generated by Django 6.0.5 on 2026-06-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_wedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='custom_venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='venue_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
