# Generated by Django 6.0.5 on 2026-06-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_wedding_custom_venue_wedding_venue_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
