# Generated by Django 6.0.5 on 2026-06-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_wedding_latitude_wedding_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='weddings/'),
        ),
    ]
