# Generated by Django 6.0.5 on 2026-06-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_wedding_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='venue_map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
