# Generated by Django 6.0.5 on 2026-06-22 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_wedding_venue_map_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.venue')),
            ],
        ),
    ]
