# Generated by Django 6.0.5 on 2026-06-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_venuemap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuemap',
            name='venue',
        ),
        migrations.AddField(
            model_name='venuemap',
            name='venue_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
