# Generated by Django 6.0.5 on 2026-07-01 17:24

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_blog'),
    ]

    operations = [

        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Admin', max_length=100),
        ),

        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=True),
        ),

        migrations.AddField(
            model_name='blog',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),

        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),

        migrations.AlterField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),

        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]