# Generated by Django 6.0.5 on 2026-07-01 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_remove_blog_keywords_blog_author_blog_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(
                    max_length=100,
                    unique=True
                )),
                ('slug', models.SlugField(
                    blank=True,
                    unique=True
                )),
            ],
        ),

        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.TextField(
                blank=True,
                default=''
            ),
        ),

        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='blogs',
                to='backend.blogcategory'
            ),
        ),
    ]