# Generated by Django 6.0.5 on 2026-07-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_blogcategory_remove_blog_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='keywords',
        ),
    ]
