# Generated by Django 6.0.5 on 2026-07-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_remove_blog_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='invitation',
            field=models.FileField(blank=True, null=True, upload_to='wedding_invitations/'),
        ),
    ]
