# Generated by Django 6.0.5 on 2026-07-04 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_wedding_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='wedding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.wedding'),
        ),
    ]
