# Generated by Django 6.0.5 on 2026-07-06 16:53

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_payment_wedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('main', 'Main Navigation'), ('footer', 'Footer')], default='main', max_length=20)),
                ('page_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('nav_priority', models.PositiveIntegerField(default=0)),
                ('show_in_navbar', models.BooleanField(default=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('robots', models.CharField(choices=[('index', 'Index'), ('noindex', 'No Index')], default='index', max_length=20)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=20)),
                ('show_in_footer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='backend.page')),
            ],
        ),
    ]
