# Generated by Django 6.0.5 on 2026-07-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_name', models.CharField(max_length=100)),
                ('groom_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('wedding_date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='wedding_cards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
